### ISSUE TITLE
python: can't open file 'workflow/scripts/noconverge.py'

### ISSUE THREAD

**Issue by gotouerina** [TurakhiaLab/ROADIES#25]
Hello, I download the software and try to run it,

my command:  python /data/01/user214/software/ROADIES/run_roadies.py  --cores 16 --mode fast --config config.yaml

**Comment by gotouerina** [comment]
I just see I used wrong eviroment, I used correct and found: 

python: can't open file '/data/01/user214/RepeatWork/10.annotation/Softmaks/workflow/scripts/noconverge.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/data/01/user214/software/ROADIES/run_roadies.py", line 17, in <module>
    subprocess.run(
  File "/data/00/user/user214/conda/envs/roadies_env/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'workflow/scripts/noconverge.py', '--cores', '16', '--mode', 'fast', '--config', 'config.yaml']' returned non-zero exit status 2

**Comment by gotouerina** [comment]
I source the evironment using 

source  /data/01/user214/software/ROADIES/roadies_env.sh

**Comment by ang037** [comment]
Hi, can you try to run the following commands:

```
cd /data/01/user214/software/ROADIES

python run_roadies.py --cores 16 --mode fast --config config/config.yaml
```

Also, make sure that the `roadies_env` environment is activated before running the following commands.

**Comment by ang037** [comment]
Hi, we haven't heard back from you on this issue for a while. Could you please provide an update or let us know if you're still facing the problem? If we don't hear from you, we'll assume the issue has been resolved and close it in a few days. Feel free to reopen it later if needed.
