### ISSUE TITLE
Details about usage section

### ISSUE THREAD

**Issue by enriquepola1996** [TurakhiaLab/ROADIES#33]
First of all, thank you very much for this nice and useful tool.

I would like to understand each of the options in the "config.yaml". I'm trying to review the "Usage section" at https://turakhia.ucsd.edu/ROADIES/#other-command-line-arguments but it doesn't direct me anywhere, could you help me?

For now I'm running by default but I'd like to know how I can configure the "config.yaml" to make a more robust analysis. I ran "python run_roadies.py --cores 8 --mode accurate" and it finished in 10 minutes with 31 genomes of approximately 35-40Mb. I'd also like to know if it's possible to set a species as an outgroup in the analysis.

I'd greatly appreciate your comments.

**Comment by enriquepola1996** [comment]
The config.yaml:

```
#This file configures the parameters for ROADIES

#Path for input genomes
GENOMES: "test/test_data2"
#Reference tree (optional, default set as null)
REFERENCE: NULL
#Length of each of the genes
LENGTH: 500
#Number of genes per iteration
GENE_COUNT: 250
#Minimum % uppercase for sampling valid genes
UPPER_CASE: 0.90
#ROADIES output directory (current iteration output in --converge option)
OUT_DIR: "output_files_fungal"
#ROADIES output directory for all iterations (only used in --converge option)
ALL_OUT_DIR: "converge_files"
#Minimum number of species in a gene fasta (4 min for ASTRAL-Pro)
MIN_ALIGN: 4 
#Minimum % match in LASTZ alignment
IDENTITY: 65
#Minimum input sequence coverage in LASTZ alignment
COVERAGE: 85
#Minimum continuity of LASTZ alignments
CONTINUITY: 85
#Max number of gene copies from a genome in an alignment
MAX_DUP: 10
#Number of steps in LASTZ sampling
STEPS: 1
#PASTA filtering parameters
FILTERFRAGMENTS: 0.50
MASKSITES: 0.02
#Threshold for high support (only used in --converge option)
SUPPORT_THRESHOLD: 0.95
#Number of instances to run in parallel
NUM_INSTANCES: 4

```

**Comment by ang037** [comment]
Hi. Thanks for using our tool. Please refer to this link: [https://turakhia.ucsd.edu/ROADIES/usage/#step-2-modify-other-configuration-paramters](https://turakhia.ucsd.edu/ROADIES/usage/#step-2-modify-other-configuration-paramters) for more details of every configuration parameters. 

You may want to run ROADIES in `--converge` mode to get an accurate converged tree with much higher `GENE_COUNT` (since `GENE_COUNT` increases with more iterations and stops once the tree is stable with confident branches). Before running the pipeline, I would suggest to set the `GENE_COUNT` to a higher number (i.e., 1000 or 2000) so that it can start doubling from that.

For faster execution, you may also want to run with more `--cores` with `NUM_INSTANCES` to set to a higher number (for example, set `NUM_INSTANCES` to 16 for `--cores 64`). 

Since you want to run for fungal genomes, you should also set the `IDENTITY` to 40 (we recently tested that with 287 fishes and it worked). 

ROADIES only generate unrooted species trees by default. You can provide a rooted reference tree (through `REFERENCE` parameter), with which ROADIES will detect the outgroup species from the reference tree and reroot the final output tree accordingly. 

Let me know if you have further queries!

**Comment by enriquepola1996** [comment]
Hello @ang037 , I did a run with python run_roadies.py --cores 8 --mode balanced --converge --config config/config.yaml but I didn't get any file as output from the tree, my yaml file is the following:

```
# This file configures the parameters for ROADIES

# Path for input genomes
GENOMES: "test/test_data2"
# Reference tree (optional, default set as null)
REFERENCE: "/home/enriquepola/ROADIES/reference_trees/tree_species_orthovenn.nwk"
# Length of each of the genes
LENGTH: 500
# Number of genes per iteration
GENE_COUNT: 1000
# Minimum % uppercase for sampling valid genes
UPPER_CASE: 0.90
# ROADIES output directory (current iteration output in --converge option)
OUT_DIR: "output_files_fungal_recomend"
# ROADIES output directory for all iterations (only used in --converge option)
ALL_OUT_DIR: "converge_files"
# Minimum number of species in a gene fasta (4 min for ASTRAL-Pro)
MIN_ALIGN: 4 
# Minimum % match in LASTZ alignment
IDENTITY: 40
# Minimum input sequence coverage in LASTZ alignment
COVERAGE: 85
# Minimum continuity of LASTZ alignments
CONTINUITY: 85
# Max number of gene copies from a genome in an alignment
MAX_DUP: 10
# Number of steps in LASTZ sampling
STEPS: 1
# PASTA filtering parameters
FILTERFRAGMENTS: 0.50
MASKSITES: 0.02
# Threshold for high support (only used in --converge option)
SUPPORT_THRESHOLD: 0.95
# Number of instances to run in parallel
NUM_INSTANCES: 4
```

Only the folders were generated:

```
(base) enriquepola@DESKTOP-62E8R2K:~/ROADIES/output_files_fungal_recomend$ ls -lh
total 1.2M
drwxr-xr-x 2 enriquepola enriquepola 4.0K Oct 15 20:56 alignments
drwxr-xr-x 2 enriquepola enriquepola  72K Oct 15 21:35 benchmarks
drwxr-xr-x 2 enriquepola enriquepola 1.1M Oct 15 21:35 genes
drwxr-xr-x 2 enriquepola enriquepola 4.0K Oct 15 21:35 genetrees
drwxr-xr-x 2 enriquepola enriquepola 4.0K Oct 15 20:56 plots
drwxr-xr-x 2 enriquepola enriquepola 4.0K Oct 15 20:53 samples
drwxr-xr-x 2 enriquepola enriquepola 4.0K Oct 15 20:56 statistics
(base) enriquepola@DESKTOP-62E8R2K:~/ROADIES/output_files_fungal_recomend$ ls statistics/
gene_dup.csv  gene_to_species.csv  homologs.csv  num_genes.csv  num_gt.txt


(roadies_env) enriquepola@DESKTOP-62E8R2K:~/ROADIES$ ls -lh converge_files/
total 4.3M
drwxr-xr-x 3 enriquepola enriquepola 4.0K Oct 15 20:53 iteration_00
-rw-r--r-- 1 enriquepola enriquepola 1.8K Oct 15 20:53 iteration_00.nwk
-rw-r--r-- 1 enriquepola enriquepola 1.6K Oct 15 20:53 iteration_00.rerooted.nwk
-rw-r--r-- 1 enriquepola enriquepola 4.7K Oct 15 20:53 iteration_00_stats.nwk
drwxr-xr-x 3 enriquepola enriquepola 4.0K Oct 15 21:36 iteration_01
-rw-r--r-- 1 enriquepola enriquepola 1.8K Oct 15 21:36 iteration_01.nwk
-rw-r--r-- 1 enriquepola enriquepola 1.6K Oct 15 21:36 iteration_01.rerooted.nwk
-rw-r--r-- 1 enriquepola enriquepola 4.8K Oct 15 21:36 iteration_01_stats.nwk
-rw-r--r-- 1 enriquepola enriquepola 2.1M Oct 15 21:36 master_gt.nwk
-rw-r--r-- 1 enriquepola enriquepola 2.3M Oct 15 21:36 master_map.txt
-rw-r--r-- 1 enriquepola enriquepola   21 Oct 15 21:36 ref_dist.csv
-rw-r--r-- 1 enriquepola enriquepola  173 Oct 15 21:36 time_stamps.csv
```

In my terminal it ends like this (last part):
[output_terminal.txt](https://github.com/user-attachments/files/17389260/output_terminal.txt)


Could you suggest something to me? I would appreciate your response again.

**Comment by ang037** [comment]
Seems like your convergence run finished in 2 iterations. Here `iteration_00.nwk` and `iteration_01.nwk` are the final species tree for both iterations.

**Comment by enriquepola1996** [comment]
Hello @ang037 

I read the documentation carefully, thank you very much for your support, everything went very well. Wait for a cite for ROADIES.
